### ISSUE TITLE
Ngx-fullpage / JQuery hijacking tab key.

### ISSUE THREAD

**Issue by ghost** [vsfedorenko/ngx-fullpage#463]
Using ngx-fullpage for the home landing page. After navigating from the fullpage section to any other section, the tab key will not move between form fields. fullPageService.destroy('all') is called in ngOnDestroy. When navigating to a component with form fields directly (or reloading the browser), thus avoiding loading the directive, the tab key works as expected with the form fields. Commenting out the element with mnFullpage directive also restores tab key functionality.

**Comment by harcomtech** [comment]
Keydown event, which calls onTab, is not being removed on destroy. Manually removing event solves it for the time being.

**Comment by glenji** [comment]
I was having this problem as well. `$(document).unbind('keydown');` in  ngOnDestroy was what solved it for me.

**Comment by rayitopy** [comment]
Also affected by this issue. I think that 
```javascript
this.fullpageService.destroy('all');
```
Should remove that listener.
